import AppKit

/// Cross-app convention (see https://nspasteboard.org) that lets pasteboard producers
/// hint at content that should NOT be captured by clipboard managers.
///
/// Honored by 1Password, Bitwarden, Maccy, Paste, and most other Mac clipboard
/// tools. When any of these markers appear alongside the pasteboard payload we
/// skip capturing the change.
public enum ConcealedTypes {
    public static let concealed  = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let transient  = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let autoGen    = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Whether the current pasteboard content should be skipped.
    public static func shouldSkip(types: [NSPasteboard.PasteboardType]) -> Bool {
        let set = Set(types)
        return set.contains(concealed) || set.contains(transient) || set.contains(autoGen)
    }
}
